### ISSUE TITLE
如何处理联动问题？

### ISSUE THREAD

**Issue by simonwoo** [alibaba/form-render#10]

**Comment by FateRiddle** [comment]
有几种方式：
1. 简单的联动可使用`"ui:hidden"`属性。可参考文档[ui:hidden的部分](https://alibaba.github.io/form-render/#/docs/ui-schema?id=%e6%8e%a7%e5%88%b6%e8%a1%a8%e5%8d%95%e9%a1%b9%e7%9a%84-ui-%e5%b1%95%e7%a4%ba%ef%bc%88%e5%85%b1%e9%80%9a%e9%85%8d%e7%bd%ae%ef%bc%89)。通过a组件选择1展示b组件，选择2隐藏b组件展示c组件的方式
2. 复杂情况可以使用自定义组件按需求自由书写
3. 非issue类的问题，建议加入我们的官方钉钉群，方便讨论（二维码在readme）
