### ISSUE TITLE
[Feature]array类型的disabled控制问题

### ISSUE THREAD

**Issue by liucien** [alibaba/form-render#103]
![B72A0122-1DA5-479b-8AF1-738B4C4EE495](https://user-images.githubusercontent.com/32785166/85106178-5c088480-b23e-11ea-831f-de7bb1e17b3d.png)
请问下，在array的状态下，disabled能做到精细控制么，比如我只想让这个两个中的其中一个禁用，而不是整个array都被禁用了

**Comment by FateRiddle** [comment]
可以的。"ui:disabled" 是支持函数表达式的，而rootValue字段可以取到这个item里所有的值
例如 "ui:disabled": {{rootValue.something === 1}}

如果这个实现还是不能满足再开一下说明哈，我先关了

**Comment by liucien** [comment]
还是达不到需要的效果，ui:disabled这个属性控制的是整个list_EWR2hE的效果

![image](https://user-images.githubusercontent.com/32785166/93301180-a6dc6d00-f82a-11ea-9654-5846aa05a9d6.png)
![image](https://user-images.githubusercontent.com/32785166/93307061-2bcb8480-f833-11ea-8c03-17852d9ae276.png)
