### ISSUE TITLE
[Feature] Will you support Material UI in the future?

### ISSUE THREAD

**Issue by hosos** [alibaba/form-render#108]
如果你们弄个 Material UI 的 mappings，我们就方便多了:)

**Comment by FateRiddle** [comment]
@hosos 短期上还有优先级更高的事儿要开发哈。写自定义组件其实并不复杂，简单来说就是写个react的组件，然后onChange和value从props取就行。欢迎参与进来扩展form-render的可用UI哦~ 有兴趣的话可以加入到我们的钉钉讨论群，或者找我私聊
