### ISSUE TITLE
[Bug]文件上传时，异步导致formData数据错误

### ISSUE THREAD

**Issue by liucien** [alibaba/form-render#109]
#107 ### 1.formRender 对应的版本，fork [codeSandbox](https://codesandbox.io/s/form-render-8k1l5) 写一个最简可复现的版本，将内容贴到下面
 - formRender 版本号：0.4.4
 - 可复现问题的 codeSandbox 地址：
无
##### 2.实际的效果以及期待效果或功能说明 
 - 实际的效果：
大文件上传时，前一份文件上传未完成，在一个新的字段内又上传了一份文件，导致数据会发生串行，新的数据会被清除掉

![index](https://user-images.githubusercontent.com/32785166/86079054-1b243180-bac2-11ea-9136-ae3fc864d4d0.gif)

 - 期待的效果或功能：
我现在的做法是加了一个蒙版loading强行让他上传完才能操作，期望异步状态下保持正确的数据更新😀

**Comment by FateRiddle** [comment]
抱歉这么迟回复。upload组件现在更新了。直接在ui:options里写props的内容，可以支持所有antd的props，随意写。
