### ISSUE TITLE
[Feature] Can "form-render" be used in native web app?

### ISSUE THREAD

**Issue by qdore** [alibaba/form-render#111]
I have an old app which generated on native js/html. It couldn't transform to a complete react app at now, but we also want to use form-render, so we want to know is it possible to use it in native web app.

Thanks~

**Comment by FateRiddle** [comment]
form-render is basically an React component. It has to be used with React dependencies. Certainly there're ways to make part of your webapp an react app without bothering other parts. Hope this helps.

**Comment by guodong** [comment]
> I have an old app which generated on native js/html. It couldn't transform to a complete react app at now, but we also want to use form-render, so we want to know is it possible to use it in native web app.
> 
> Thanks~

What a great issue  here is!
