### ISSUE TITLE
[Feature]能否增加一个空的组件库，只提供自定义组件注册

### ISSUE THREAD

**Issue by liucien** [alibaba/form-render#112]
有些项目并不想使用antd或者fusion，也不想拉取整个项目进行修改，只想在本地维护一份组件作为自定义组件注入

**Comment by FateRiddle** [comment]
可以直接 import FR from 'form-render' 这个是不带任何组件库的纯粹版本。需要你自己注入 mapping 和 widgets。mapping 可以参考 https://github.com/alibaba/form-render/blob/master/src/widgets/antd/index.jsx
注入方式可以参考 https://github.com/alibaba/form-render/blob/master/src/antd.js
