### ISSUE TITLE
[Bug] 颜色选择器没有将透明度正确展示

### ISSUE THREAD

**Issue by jing-wu** [alibaba/form-render#113]
##### 1.formRender 对应的版本，fork [codeSandbox](https://codesandbox.io/s/form-render-8k1l5) 写一个最简可复现的版本，将内容贴到下面
 - formRender 版本号：0.6.0-beta.1

##### 2.实际的效果以及期待效果或功能说明 
 - 实际的效果：将值 'rgba(204, 36, 36, 0.5)' 拷贝进颜色选择器的输入框，预览处显示的颜色是不带透明度的，即显示的是 'rgba(204, 36, 36, 1)' 的颜色
 - 期待的效果或功能：能正确预览颜色

**Comment by FateRiddle** [comment]
谢谢你的pr，0.6.0发布，color已经支持opacity。
