### ISSUE TITLE
[Feature] 希望能够支持接口提供下拉sug数据

### ISSUE THREAD

**Issue by qdore** [alibaba/form-render#114]
对于输入控件，往往会遇到需要使用服务器api提供sug数据的情况

**Comment by FateRiddle** [comment]
这种情况一般是写一个自定义组件来完成的。参考文档和demo都有哦~ https://alibaba.github.io/form-render/#/docs/widget
简单的说，就是直接拿antd的demo，把value和onChange改一改就是自定义组件了。注入方式也参考文档。
