### ISSUE TITLE
[Feature]ui:options 配置希望能够有全局配置，不需要每次都在 schema 里配置

### ISSUE THREAD

**Issue by Yokubee** [alibaba/form-render#119]
很多定制化的需求，都需要全局通用，如果每次都遍历 schema 所有元素进行设置很麻烦，不利于后续维护。因此建议可全局设置，作为初始化的 props 传入即可。

**Comment by kyo4311** [comment]
你可以自己封一个组件啊!

`const MyFormRender= (props:any) => {
  const myWidgets={{ cascade: Cascade }};
  return <FormRender
        {...props}
        widgets= {{...props.widgets, ...myWidgets }}
      />
}
`

**Comment by tw93** [comment]
楼上正解
