### ISSUE TITLE
通用参数中当Format时dateTime类型的时候如何控制时间的format？

### ISSUE THREAD

**Issue by ColinChen2** [alibaba/form-render#12]
如何定义日期的输出格式，比如输出成，"YYYY/MM/DD"

在官网例子中[demo](https://alibaba.github.io/form-render/docs/demo/index.html)
选择关于日期的配置里
```
"date2": {
        "title": "日期选择",
        "type": "string",
        "format": "date",
        "ui:options": {
          "format": "YYYY/MM/DD"
        }
      }
```
 - formRender 版本号：最新版本
 - 可复现问题的 codeSandbox 地址：官网

##### 2.实际的效果以及期待效果或功能说明 
 - 实际的效果：
[
![Screen Shot 2019-11-14 at 3 18 12 PM](https://user-images.githubusercontent.com/7310875/68835322-b95db580-06f2-11ea-8de9-aec4115ef729.png)
](url)
 - 期待的效果或功能：

1. 组件时间显示为2019/11/14
2. data输出"date2": "2019/11/14",

BY THE WAY
通用参数中的【format】给人以迷惑，第一眼看，不知道干嘛的。参照【don't make me think】的设计原则，建议使用其他术语，比如【element】，也比较符合现在的数据抽象维度。

**Comment by FateRiddle** [comment]
谢谢你的反馈，问题已经排查。form-render每周一定期发布。
关于最后一个问题，form-render遵循了JSON Schema的国际规范，使用的字段是有严格规范的。
p.s. 定义日期显示格式的字段，format感觉更恰当吧

**Comment by FateRiddle** [comment]
https://github.com/alibaba/form-render/blob/master/CHANGELOG.md 已解
