### ISSUE TITLE
[Feature]FR全局支持 modal 属性

### ISSUE THREAD

**Issue by karzanOnline** [alibaba/form-render#120]
**Is your feature request related to a problem? Please describe.**
在实际业务中，使用的 formRender 展示将超出当前屏幕很多。对用户体感很差，无法一眼看到当前的结构。同时用户修改时 期望可以快速所引导目标位置。

**Describe the solution you'd like**
将 modal 属性放置到默认配置(全局的)中，并默认为一个<a>标签，访问内容时可以逐个点开看里面的细节。

**Additional context**

![](https://img.alicdn.com/tfs/TB1.4DAOrY1gK0jSZTEXXXDQVXa-1960-258.png)

**Comment by FateRiddle** [comment]
已经支持。
