### ISSUE TITLE
[Feature] 是否可能增加一些例子

### ISSUE THREAD

**Issue by kyo4311** [alibaba/form-render#126]
看了一下感觉还是很不错的，是不是可以增加一些例子，让使用者增强信心？
1. 有编辑页的情况，一进页面就会填一些值。
2. 如果上次提交的表单的值要存起来，然后下次进来自动加载这些初始值。

**Comment by FateRiddle** [comment]
可以的，文档刚翻新了，可以体验一下新的文档。
因为formData就是存在state里的，所以需要一进来就有一些formData，只要setState就行了
