### ISSUE TITLE
[Feature] Input box can display text length in real time

### ISSUE THREAD

**Issue by rccoder** [alibaba/form-render#127]
![image](https://user-images.githubusercontent.com/7554325/88998176-04bd0000-d324-11ea-8cc6-5e21a479232f.png)

目前输入框支持文字长度校验，但只能离开的时候进行校验

期望能在输入的过程中有个提示，如上图所示

同时，目前的长度限制是直接 length，建议支持 英文或数字 算半个字

可以用这个判断

``` js
'你好aaa'.match(/[\u4e00-\u9fa5]/g)
```
![image](https://user-images.githubusercontent.com/7554325/88998321-51084000-d324-11ea-9fa8-9f0d5a5b9203.png)

**Comment by FateRiddle** [comment]
0.7.2 fixed。谢谢建议。

**Comment by rccoder** [comment]
Cool
