### ISSUE TITLE
FormRender 选择展示有问题需要优化

### ISSUE THREAD

**Issue by tw93** [alibaba/form-render#132]
FormRender 的展示
![image](https://user-images.githubusercontent.com/8736212/89892721-adfbd400-dc09-11ea-8947-0c616de7224e.png)

期待的样子，对于 switch 和 单选位置其实需要对齐的，现在太丑了
![image](https://user-images.githubusercontent.com/8736212/89892798-cf5cc000-dc09-11ea-907c-df38d37aeaa4.png)
![image](https://user-images.githubusercontent.com/8736212/89892813-d683ce00-dc09-11ea-8e73-f6bb6f7e483b.png)

**Comment by FateRiddle** [comment]
这个是 fr-generator 侧的展示问题，在form-render里其实是ok的，那边也已经解了~
