### ISSUE TITLE
fr-generator  关于 antd 样式污染的问题

### ISSUE THREAD

**Issue by lmnsg** [alibaba/form-render#134]
fr-generator 中引入了 antd4.x ，我的项目中使用的是 3.x，会导致 antd 的样式被污染，看看能不能组件内隔离下

**Comment by a8b7** [comment]
document.getElementsByTagName('aside').item(0).classList.remove("ant-layout-sider");

**Comment by FateRiddle** [comment]
issue建议提在 https://github.com/form-render/schema-generator
我会把 antd 作为 peerDependency 放出来解决这个问题，同时也解决了现在引入 fr-generator 会有两份独立的 antd 的尴尬。
不过建议小伙伴们 antd 可以往 4 升级了哦，毕竟之后 form-render 都不会考虑对 antd 3和4之间的兼容，统一默认是4版本。一般其实还好，但指不定哪里就会有问题~
