### ISSUE TITLE
[Feature] Some optimizations of the array structure in the collapsed state

### ISSUE THREAD

**Issue by rccoder** [alibaba/form-render#135]
## 背景

目前的数据类型的展现实现的非常棒，能自由拖动换顺序，配置完成之后也会自动收起来。

在使用的过程中，发现了一些新的问题，希望能帮之优化

## 诉求

![image](https://user-images.githubusercontent.com/7554325/90129276-ed0d5f00-dd9a-11ea-8c83-653b0b13446b.png)

1. ` "type": "range", "format": "dateTime",` 在收起状态下会显示成复杂结构，期望能展示（需要兼容下没填的情况）
2. 收起状态下，目前显示的是前三个，期望显示哪前三个能自己配置。这样在收起的状态下体感会好很多
3. 期望收起时，有能力不显示名称（如上图中的 别名、日期范围等）。或者有更好的方式来展示这种东西（比如表格？）

**Comment by FateRiddle** [comment]
form-render 1.0版本会使用table等更好的ui规范来解决哈。本周发版。
