### ISSUE TITLE
[Bug]FR 一排多时，个别"短"组件 会出现排版不对齐问题

### ISSUE THREAD

**Issue by karzanOnline** [alibaba/form-render#136]
FR 一排多时，个别"短"组件 会出现排版不对齐问题
![image](https://user-images.githubusercontent.com/16421478/90600535-5375ff80-e229-11ea-907f-6c73b59f95de.png)

这里建议找到这个临界逻辑，排版需要整齐。

**Comment by FateRiddle** [comment]
这个是个非常尴尬的已知问题

<img src='https://user-images.githubusercontent.com/12005259/91147170-78b3b380-e6ea-11ea-9a03-b4b635d7d9d0.png' width='400px' />

例如是分行的时候，展示是不希望上部有空间的，但是如你提的情况就需要。然而这个判断非常非常得复杂。

建议此类情况使用 displayType=“row” 的方式优雅地去避免。参考了antd等设计规范，一般一行多个的场景，label也都是和field同行的（就是 displayType=“row”）这个配置

未来会考虑一下更好的解法，目前建议如上，谢谢issue。

**Comment by F-loat** [comment]
这个问题好像是横向排列时不设置 title 就会有？之前用的一个[表单方案](https://github.com/ncform/ncform/blob/master/CONFIG_CN.md)是通过 `showLabel` 和 `noLabelSpace` 两个属性配合来规避的，可以参考下 @FateRiddle 

```
{
  label: '', // 标签内容【支持dx表达式】
  showLabel: true, // 是否显示标签（注意：当为 false 时，依然占着空间）
  noLabelSpace: false, // 标签是否不占空间，优先级比showLabel高
}
```
