### ISSUE TITLE
增加cdn使用方式和 表单编辑状态和非编辑状态控制

### ISSUE THREAD

**Issue by zhugunzi** [alibaba/form-render#14]
能否增加cdn ,html文件直接quick start的demo!
对于表单 能否增加 noform 中的 详情和禁用编辑的状态控制属性

**Comment by tw93** [comment]
cdn 这个方式可以通过  http://unpkg.com/form-render/dist/antd.js 去尝试，但是很不推荐，快速开始建议用 https://codesandbox.io/s/form-renderjichudemo-8k1l5?fontsize=14 来玩
表单 详情和禁用编辑的状态控制属性现在可以通过 https://alibaba.github.io/form-render/#/docs/ui-schema 来弄
