### ISSUE TITLE
服务端渲染 form-render/lib/index.js 文件中直接引用 css 文件导致执行报错

### ISSUE THREAD

**Issue by FrendEr** [alibaba/form-render#143]
因为项目使用了服务端渲染，在运行的时候报了 css 代码语法解析错误
```
.fr-wrapper .outline { outline: 1px solid; }
^

SyntaxError: Unexpected token '.'
```

看了下编译后的代码 ` form-render/lib/index.js ` 中引用了 css 文件 
```
require("./atom.css");

require("./index.css");
```

是否可以将样式与 js 代码剥离，提供一套类似 antd 的加载方案呢？

**Comment by FrendEr** [comment]
@tw93 @FateRiddle 请教一下以上问题有没有好的解决方案呢？

**Comment by FateRiddle** [comment]
这个我需要研究一下哈，现在暂时没有完整的解答，因为之前确实没有考虑过SSR的事儿。有兴趣可以加一下我们的钉钉群交流一下。

**Comment by FrendEr** [comment]
> 这个我需要研究一下哈，现在暂时没有完整的解答，因为之前确实没有考虑过SSR的事儿。有兴趣可以加一下我们的钉钉群交流一下。

好的，期待官方解决方案

**Comment by FrendEr** [comment]
@FateRiddle 你好，请问这个有支持的计划吗？

**Comment by lyboy2012** [comment]
有结论吗
