### ISSUE TITLE
考虑支持下动态表达tab

### ISSUE THREAD

**Issue by Bestfeel** [alibaba/form-render#145]
1. 考虑支持下动态表达tab,使用场景，当配置项叫多的时候如果配置在一个页面里面容易配置错误，而且显示不是很直观。 如果能支持分tab自定义分类的话就非常赞👍 了。

**Comment by FateRiddle** [comment]
@Bestfeel 这个的schema想好了，在开发中。但是突然觉得，你需要的是tab还是step呢？表单分几个tab，往往是有顺序的吧？

**Comment by quicklearning123** [comment]
请问tab什么时候能用上

**Comment by FateRiddle** [comment]
tab类型会作为list的一种展示形式。在form-render 1.0版本将会陆续支持。
但是，如果表单内容过长的情形，我的建议还是使用多个form-render，这样每个页都可以单独处理和保存。
