### ISSUE TITLE
formData影响表单控件显隐

### ISSUE THREAD

**Issue by johnnylc** [alibaba/form-render#15]
实际效果：当formData不包含propsSchema中定义的properties字段时，对应字段的控件会被隐藏；
期待效果：propsSchema中定义的properties字段始终显示，formData仅控制表单项数值，而不影响控件显隐。
从个人理解，formData负责控制表单数值，而显隐应该通过ui选项或者联动控制。

示例：
https://codesandbox.io/s/form-render-9b89e
使用空对象formData时，表单不显示；
若取消render中onChange={this.onChange}注释，表单渲染会调用onChange从而更新formData显示正常。

**Comment by FateRiddle** [comment]
不知道你是否认同，初始化表单的data是必要的，在没有data的数据结构情况下无法构建一个表单的UI。单选框需要初始值，对象和列表更需要初始值。由于form-render是受控组件（个人认为这是优点），formData是存在外部的，所以初始化的函数也必须是外部方法，onChange显然最适合这个工作，所以目前form-render确实是用onChange来初始化表单的。

我承认对于初写demo的同学，如果忘记写onChange方法会出现“表单怎么不渲染也不报错”的困惑。不过除此以外，你觉得使用onChange来初始化会有什么实际应用上的不便吗？

**Comment by johnnylc** [comment]
我的应用场景是两个表单共用数据源的渲染，例如搜索表单SimpleSearchForm和ComplexSearchForm两个表单，两者分别展示相同的搜索数据，只是展示形式不同。
![image](https://user-images.githubusercontent.com/12717523/69148042-5c0c9e80-0b0e-11ea-8a6b-eb9793f3b697.png)

![image](https://user-images.githubusercontent.com/12717523/69148061-662e9d00-0b0e-11ea-9059-83df796440b2.png)


其中，简单表单中只有name字段，复杂表单中存在name，age，gender等字段，两者共用一个formData。按照我的思路，将formData放入页面上层组件的store中，然后通过props分别传入SimpleSearchForm和ComplexSearchForm中，来同步控制两个表单的数据。如果在store中定义formData为空对象而不使用onChange进行初始化，则会无法显示。
在两个Form中使用onChange对store中的formData初始化的话，获得的formData也是不一致的（form字段不同）。
除非给formData手动添加全部表单项的初始值。

不知道对于这中场景有没有更好的实现形式？

**Comment by johnnylc** [comment]
关于表单是受控组件这一点我非常赞同的。
其实问题出在formData与展示控件之间的关系上，比如formData中不存在name字段 那么name字段对应的input是否显示，这类情况在后端接口返回数据不完整（比如返回值中某字段不存在）的情况下也会经常遇到，不知道有没有标准的解决方式。

**Comment by FateRiddle** [comment]
@johnnylc 
展示的不同，最简单的方法是使用ui:hidden字段隐藏不需要的字段。
至于两个表共用一份state的情况，共用一个onChange方法就能保持数据一致。

1. 你提及的问题是formData => schema 的一个解析器。可以更具自己的情况简单写一个。fr之后也打算提供此类方法，如果有兴趣可以参与，提交pr哦，欢迎加入我们的Dingding群方便交流。
2. 不建议。

我先关了，后续还有疑问再开。
