### ISSUE TITLE
[BUG]表单类型为number 输入值为0时没有触发pattern校验

### ISSUE THREAD

**Issue by taoxiaohang** [alibaba/form-render#150]
<img width="387" alt="企业微信截图_e6a59e29-442c-4bba-a513-4631d30c66d8" src="https://user-images.githubusercontent.com/20037841/92357400-596d4b00-f11a-11ea-8915-c1c0cf5b552a.png">
<img width="387" alt="企业微信截图_e6a59e29-442c-4bba-a513-4631d30c66d8" src="http://s1.wacdn.com/wis/538/1b2fc1720effb035_790x456.png">
当表单类型为number 输入值为0 没有触发pattern的校验
<img width="387" alt="企业微信截图_e6a59e29-442c-4bba-a513-4631d30c66d8" src="http://s1.wacdn.com/wis/538/f546ab4aeddd05a8_247x83.png">

**Comment by taoxiaohang** [comment]
formRender 版本号：0.4.4

**Comment by taoxiaohang** [comment]
@FateRiddle

**Comment by FateRiddle** [comment]
谢谢issue，已经修复。
