### ISSUE TITLE
README“设计理念”的链接打开404

### ISSUE THREAD

**Issue by fayeah** [alibaba/form-render#153]
- `README.md`文件里面有一个链接，“设计理念”，打开的地址为：https://github.com/alibaba/form-- 
- render/blob/master/guide/design/what，但是页面显示404。
我认为是path的问题，因为我发现design.md在docs/guide路径下。但是当我尝试打开‘https://github.com/alibaba/form-render/blob/master/guide/design’或是‘https://github.com/alibaba/form-render/blob/master/guide/design.md’的时候，也是404.

能不能指导一下，我想自己尝试修复。谢谢～

**Comment by tw93** [comment]
感谢感谢 我看你已经修复了，谢谢，后续欢迎一起来维护 FR

**Comment by fayeah** [comment]
一起学习

**Comment by fayeah** [comment]
> 感谢感谢 我看你已经修复了，谢谢，后续欢迎一起来维护 FR

hi， 想问下FR有打算加单元测试吗？如果想要重构某段代码，如何知道是否会有其他的影响呢？

**Comment by FateRiddle** [comment]
@fayeah 暂时没有加，说实话1是不知道咋写，2是怕投入很多收效很小不值得。之前看到前端单测主要是写state管理的部分（比如dva），UI变化描述上写单测，俺还不太了解咋写。state管理上FormRender其实没啥复杂的地方。

至于你提的问题，一般每个utils都有明确是干啥事儿的，单一功能原则，那块的重构应该还算友好。其他部分嘛。。。总之，你有没有建议？

**Comment by fayeah** [comment]
@FateRiddle 说不上建议，我是抱着学习的态度来的。我只是提出了这么一个疑问，但是我发现其实像react和vue他们都是有单元测试，应该说它们比较复杂，用的也非常广泛，虽然也不知道他们啥时候开始加的...可以分析一下单元测试的优缺点，然后可以的话先加几个简单的用例呢？FR毕竟也是一个开源的库，说不定有人喜欢写测试呢（不是说我……）
