### ISSUE TITLE
Advice: Move alicdn resources to local

### ISSUE THREAD

**Issue by colordove** [alibaba/form-render#158]
For example, `Delete Icon` which is load form https://img.alicdn.com/tfs/TB12VseTuL2gK0jSZPhXXahvXXa-128-128.png

In some cases, Our application works in no external network environment, So `Delete Icon` will fail to load.

**Comment by FateRiddle** [comment]
ok, it's reasonable. I'll use base64 for icon usage in the next version.

**Comment by FateRiddle** [comment]
Fixed in this version. https://github.com/alibaba/form-render/pull/192/commits/92c462bf48b8658848626d1f27ee279617db52bf
