### ISSUE TITLE
[Feature]支持表单分区块展示

### ISSUE THREAD

**Issue by purelanren** [alibaba/form-render#159]
**目前的表单分区块展示只能在原数据外包裹一层对象，无法支持只在前端展示层面分区。🌰如下：**

### 期望效果
<img src="https://user-images.githubusercontent.com/8475155/93041931-5cb78800-f680-11ea-9d65-d0fab6b98251.png" width="300" />

### 目前的数据结构只能如下
<img src="https://user-images.githubusercontent.com/8475155/93042170-f717cb80-f680-11ea-96bd-14b4f4a88d13.png" width="300" />

### 期望实现
<img src="https://user-images.githubusercontent.com/8475155/93042075-bfa91f00-f680-11ea-99e8-08dfc67a94aa.png" width="300" />

**Comment by taoxiaohang** [comment]
"splitName": {
        "type": "html",
        "default": "<h4>区块一</h4>"
      },

但是会导致splitName作为一个参数保存

**Comment by FateRiddle** [comment]
已经进入开发排期

**Comment by Tanviw** [comment]
请问这个大概能在什么时候实现呢？

**Comment by FateRiddle** [comment]
通过新的bind字段，能是的展示和formData的结构分离化，在form-render 1.0已经支持，本周发版
