### ISSUE TITLE
boolean类设置必填时，选择flase时必填校验不通过

### ISSUE THREAD

**Issue by lyl-moon** [alibaba/form-render#162]

**Comment by FateRiddle** [comment]
这个版本已经修复为不会提示校验不通过了。

不过我想质疑一下给boolean类加required场景逻辑是否真的合理。在展示上没选和选择false没有任何可见区别。场景上我们覆盖到现在也没有出现过一例需要给boolean类require的情况。

如果真的需要区分不填和填false，建议使用下拉选择。选择项设为“是”和“否”，default：null

**Comment by lyl-moon** [comment]
感谢修复此问题。(其实我也觉得不合理，但是我们领导给我提了这个问题，所以就麻烦你们啦)

**Comment by FateRiddle** [comment]
稍等，版本还没发。我把解了问题先回复了，好不重复看问题。明天发。
