### ISSUE TITLE
钉钉群二维码无效

### ISSUE THREAD

**Issue by fayeah** [alibaba/form-render#163]
readme上面有一个钉钉聊天群：
![image](https://user-images.githubusercontent.com/29644978/93161933-365c2000-f746-11ea-8146-fc0b4e914891.png)

无法扫描加入

**Comment by FateRiddle** [comment]
<img src="https://img.alicdn.com/tfs/TB1CprJg5pE_u4jSZKbXXbCUVXa-894-1087.jpg" width="300px" />
先可以扫这个，尴尬，忘记换了。
文档今天会翻新修复这个问题，欢迎欢迎加入哈！感谢你的pr。

**Comment by StrongerD** [comment]
> <img alt="" width="300px" src="https://camo.githubusercontent.com/9d8289d19b14cefd78193f15ef97df5e66b83605b36f43e7ac0c9ebee0a88548/68747470733a2f2f696d672e616c6963646e2e636f6d2f7466732f5442314370724a673570455f75346a535a4b6258586243555658612d3839342d313038372e6a7067">
> 
> 先可以扫这个，尴尬，忘记换了。 文档今天会翻新修复这个问题，欢迎欢迎加入哈！感谢你的pr。

麻烦更新一下最新的群二维码
