### ISSUE TITLE
使用 https://x-render.gitee.io/schema-generator/ 官网demo本地运行，编辑组件属性，组件消失

### ISSUE THREAD

**Issue by ibeizhu** [alibaba/form-render#164]
组件版本号 "fr-generator": "^0.5.2"

重现步骤：
1、将  https://x-render.gitee.io/schema-generator/ 页面demo 粘贴到本地工程，安装fr-generator
2、编辑任意组件属性的标题，组件消失

**Comment by FateRiddle** [comment]
请在 https://github.com/form-render/schema-generator 上提这个issue 哈
