### ISSUE TITLE
[BUG] ui:options传递自定义参数，某个值类型是方法，渲染的时候会自动执行这个方法

### ISSUE THREAD

**Issue by reidzhou** [alibaba/form-render#166]
测试shcema
`
const schema = {
  type: 'object',
  properties: {
    string: {
      title: '网址',
      type: 'string',
      'ui:widget': 'siteInput',
    },
    select: {
      title: '单选',
      type: 'string',
      enum: ['a', 'b', 'c'],
      enumNames: ['选项1', '选项2', '选项3'],
      'ui:widget': 'radio',
      'ui:options': {
        test: ()=>alert(1)
      }
    },
  },
};
`

**Comment by reidzhou** [comment]
这个问题能不能优先解决一下

**Comment by FateRiddle** [comment]
这个问题的原因我大致明白了。
```js
 input1: {
      title: '输入框',
      description: '尝试输入超过5个字符',
      type: 'string',
      'ui:hidden': (formData, rootValue) => formData.select === 'b',
    },
```
例如会有这样需要动态计算schema值的问题，使用的就是函数表达式。会在使用时直接执行。传函数进去也是需要的，我需要想一下比较好的方案。

**Comment by reidzhou** [comment]
嗯，不过我觉得自定义参数里面的函数立马执行的情境很难会有吧，反而是组件内部手动调用偏多

**Comment by FateRiddle** [comment]
可以看一下文档“如何联动”部分。函数表达式目前用于表述一些表单联动的情况。

**Comment by zhangchen915** [comment]
ui:options 可以暂时写一个方法返回要传入的函数   `() => () => {}`

**Comment by FateRiddle** [comment]
@zhangchen915 抱歉这段贼忙，回复迟了。谢谢回复提醒哈。() => () => {} 这个方式我测试了下是现在版本已经支持的。

不过这个作为开放api感觉不是那么友好，也许有更好解法，不知道你有没有更好的建议？我需要再思考一下，没有更好的方案就先采用你提的这个方式开放一个api。

有后续问题可以再开，我先关了
