### ISSUE TITLE
看大佬近期优化了下表单校验的debounce，但还是感觉不大合理，手动触发校验而不是change时触发所有的表单项校验

### ISSUE THREAD

**Issue by yansu1** [alibaba/form-render#168]

**Comment by FateRiddle** [comment]
手动可以触发。把showValidate 改成 true（这个也是之前的默认行为），就会展示所有校验。就是用户意义的“手动触发校验”。

其次，有个误区，onValidate 不是用户意义上的“触发校验”，而是同步校验信息到state。

form-render是可控组件。所以状态是时时同步到state的，debounce只是为了比如input输入的时候，不要每输入一个字母就同步一次。
