### ISSUE TITLE
请问，支持antd3.x吗？

### ISSUE THREAD

**Issue by Aledenn** [alibaba/form-render#171]

**Comment by FateRiddle** [comment]
4和3不能同时支持。也不打算同时支持。升4吧，很平滑的。

**Comment by FateRiddle** [comment]
0.7.3 之前antd版本并不依赖外部，所以可以放心使用（就是FR会独立装一版antd）
0.4.5 之前form-render内部使用的也是 antd v3
@Aledenn

**Comment by vision-ken** [comment]
我们主工程的用的ant3.22，如果不升级的话，能否使用最新的form-render版本？或者最高能使用说明版本？
