### ISSUE TITLE
组件数据关联实现

### ISSUE THREAD

**Issue by monijiang** [alibaba/form-render#176]
![image](https://user-images.githubusercontent.com/20900383/94221196-2cdc7000-ff1d-11ea-91a4-1f81e4f943fb.png)

有两个表单，需要他们的输入值相加和为100。除了自定义组件实现的方式，有办法通过联动实现吗？

下方通过设置maximum，minimum相同的值，来进行校验，作为正常json对象，传递变量是可以实现的。改写为模板字符串，没有触发

{
  "schema": {
    "type": "object",
    "properties": {
      "examSample": {
        "title": "训练集",
        "type": "number",
        "default": 80,
        "maximum": "{{100 - formData.testSample === formData.examSample ? 100 - formData.testSample : 100 - formData.testSample }}",
        "minimum": "{{100 - formData.testSample === formData.examSample ? 100 - formData.testSample : 100 - formData.testSample }}",
        "ui:options": {
          "addonAfter": "%"
        }
      },
      "testSample": {
        "title": "测试集",
        "type": "number",
        "default": 20,
        "ui:options": {
          "addonAfter": "%"
        }
      }
    }
  },
  "formData": {
    "examSample": 0,
    "testSample": 20
  }
}

**Comment by monijiang** [comment]
查看源码时，发现asField.jsx文件中，除了几个像options，hidden的单独处理，对于schema中的字段转换只包含下述枚举，可以扩展下方数组，增加maximum和minimum，实际的大小检验函数中也并没有使用min和max.
let _schema = { ...schema };
    Object.keys(schema).forEach(key => {
      const availableKey = [
        'title',
        'description',
        'format',
        'pattern',
        'message',
        'min',
        'max',
        'step',
        'enum',
        'enumNames',
      ];
      // TODO: need to cover more
      if (availableKey.indexOf(key) > -1) {
        _schema[key] = convertValue(schema[key], formData, rootValue);
      }
    });

**Comment by FateRiddle** [comment]
@monijiang Sorry for the late reply. I've accepted your pull request, and I suppose that will solve this problem, so I'm going to close it, feel free to reopen it for further discussion.
By the way, I can't really understand your issue. If it is through google translator, you may post in your native language, or maybe try best to describe it in English. Either way will be easier for understanding than seemingly translated gibberish. 
Thanks again for your PR support!
