### ISSUE TITLE
阅读base/resolve源码时候的疑问

### ISSUE THREAD

**Issue by terryz95** [alibaba/form-render#178]
https://github.com/alibaba/form-render/blob/d3a79bc6326f77109c83d253c388a9d2bc3ef669/src/base/resolve.js#L62-L65

这个checkRequired的opt貌似没有看到有任何地方可以传入进行改变？option从一开始传入的时候就是`{}`，递归到内部不也都是`{}`？

**Comment by Sijia1998** [comment]
<img src="https://user-images.githubusercontent.com/29126094/96538017-25b14380-12ca-11eb-9d05-f547c15761fa.png" width="300" height="400"/>
@terryz95 欢迎同学加入我们的开源群组，有任何想法和疑问都可以进行讨论哦
