### ISSUE TITLE
angularjs 可以用吗

### ISSUE THREAD

**Issue by chenshun00** [alibaba/form-render#18]
angularjs 可以用吗？
如果可以是否可提供部分例子 :)

**Comment by FateRiddle** [comment]
实话实说，目前不支持，对angular的支持短期也不是重心。不过项目开源就是希望能集思广益，在大家的集体智慧和努力下把东西做好，所以我们欢迎任何pr和建设性的讨论，如果感兴趣可以加入我们的钉钉群，群里不少人提到希望支持vue，现在正考虑实现的可能性。所以一切皆有可能，期待你的加入。
