### ISSUE TITLE
希望能优先解决下：设置ui:hidden目前只控制了UI展示效果，提交时formData并没有控制

### ISSUE THREAD

**Issue by yzdymHe** [alibaba/form-render#181]
当json很大时，设置了很多ui:hidden，提交时隐藏项不应传值，手动处理工作量大，不灵活

**Comment by F-loat** [comment]
建议增加 `ui:remove` 之类的字段进行控制，隐藏和移除都有其适用场景，交给用户配置会好一些

**Comment by FateRiddle** [comment]
这个其实一直想做的，但是隐藏数据涉及到底层的大幅改造，需要给我们一点兼容的时间。

**Comment by mixtan** [comment]
> 这个其实一直想做的，但是隐藏数据涉及到底层的大幅改造，需要给我们一点兼容的时间。
> 本需求已经进入开发周期。

@FateRiddle 请问这个需求完成发版了吗？

**Comment by FateRiddle** [comment]
旧版的构架下支持这个功能有相当大的改造成本。form-render 1.0版本已经支持。本周发版。
