### ISSUE TITLE
Color组件宽度问题

### ISSUE THREAD

**Issue by zhousufa** [alibaba/form-render#182]
![image](https://user-images.githubusercontent.com/3891137/95644550-f9d3d800-0ae9-11eb-9d29-7bf26a2ed500.png)
见图，超出容器了

**Comment by FateRiddle** [comment]
请问你使用的是antd v4吗？我看在antd的class里面已经默认给input加上了width: 100%的样式，fusion侧我也手动加了内联的width：100%。或者看看是否在顶层有样式定制的覆盖

在这次代码更新里也手动给输入框补了width:100%，如果还有问题再开。可能的最好带一个最小复现的demo，方便迅速排查谢谢。
