### ISSUE TITLE
怎么设置placeholder？

### ISSUE THREAD

**Issue by bytrix** [alibaba/form-render#187]

**Comment by fayeah** [comment]
![image](https://user-images.githubusercontent.com/29644978/96371278-76725080-1193-11eb-9fd9-f95a32fe8e27.png)

@bytrix 不知道是不是你想要的答案，如果不是，请详细描述一下你的问题，谢谢。

**Comment by Sijia1998** [comment]
@bytrix 可以参考 @fayeah 同学给出的解决方案
