### ISSUE TITLE
[bug] 当maximum为浮点数时校验失败

### ISSUE THREAD

**Issue by taoxiaohang** [alibaba/form-render#188]
![image](https://user-images.githubusercontent.com/20037841/95954405-d54f6700-0e2d-11eb-9a41-15e7a4aad639.png)
![image](https://user-images.githubusercontent.com/20037841/95955871-15174e00-0e30-11eb-8c24-d8b4dfc08eab.png)

**Comment by taoxiaohang** [comment]
@FateRiddle

**Comment by FateRiddle** [comment]
@fayeah 已经fixed
