### ISSUE TITLE
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by jymsy** [alibaba/form-render#197]
![image](https://user-images.githubusercontent.com/2777671/97396412-ff228680-1921-11eb-9bd5-1ab8dbc7a3ac.png)

we use react 16.14.0 and form-render 0.8.7 in our project.

Maybe we should remove react from dependencies?
![image](https://user-images.githubusercontent.com/2777671/97396928-0f873100-1923-11eb-8456-f1e605d54fbd.png)

**Comment by FateRiddle** [comment]
My bad, we'll fix this and publish a new version today.
