### ISSUE TITLE
list数据处理默认值的时候可以同时支持对null值和undefined进行容错吗？

### ISSUE THREAD

**Issue by BeanWei** [alibaba/form-render#199]
https://github.com/alibaba/form-render/blob/3ee977336699b841d043e0208b3fcf72e7320c2a/src/base/resolve.js#L68

**Comment by FateRiddle** [comment]
@BeanWei 就是说，你希望data是null的时候，也展示默认么？
这儿的逻辑是 undefined 表示肯定没有赋初始值，这种情况用default值，一旦赋值了就不再使用default值。

**Comment by BeanWei** [comment]
> @BeanWei 就是说，你希望data是null的时候，也展示默认么？
> 这儿的逻辑是 undefined 表示肯定没有赋初始值，这种情况用default值，一旦赋值了就不再使用default值。

@FateRiddle  正常来说如果后台接口数据足够规范是不会有这个问题的。但是也会有后台返回值是null的情况吧，这样如果一个字段的值是数组类型但是后台给的却是null那么form-render的list组件遍历值的时候取的是null而不是默认空数组就会报错。

**Comment by FateRiddle** [comment]
会报错么？你可以试着升级一下，报错的问题应该在之前版本已经兜底了。
null值使用默认个人感觉还合理的，下周的版本修复。
