### ISSUE TITLE
能否将组件的key写入外层的DOM结构中，以方便获取DOM节点

### ISSUE THREAD

**Issue by liucien** [alibaba/form-render#207]
在某些嵌套结构中需要单独获取某个DOM节点进行操作，因为整个树都是循环出来的，没有独立标识，只能靠title属性进行获取，感觉不是很好，是否能开放出data-id=xxx这种进行区分

**Comment by FateRiddle** [comment]
有`ui:className`属性可以给单个节点加class的。然后就能找到对应dom了。
