### ISSUE TITLE
能否吧原来的textarea，设置为富文本编辑器，或者自己集成第三放富文本编辑器，能支持些复杂的功能😊😊😊😊😊😊😊😊😊😊

### ISSUE THREAD

**Issue by y5621857** [alibaba/form-render#208]
能否吧原来的textarea，设置为富文本编辑器，或者自己集成第三放富文本编辑器

**Comment by y5621857** [comment]
能支持些复杂的功能，如bartf-editor，本来想二次开发集成bartf-editor，打包已被各种报错虐死了😊😊😊😊😊😊😊😊😊😊

**Comment by FateRiddle** [comment]
可以的，我们内部已经在用一个了，下周会放出自定义组件的仓库，统一在form-render下用lerna管理。会陆续把此类自定义组件沉淀到这里，文档也会陆续补充。同时非常欢迎你们在使用的自定义组件发PR，好的我们会纳入官方版本 ：D
