### ISSUE TITLE
后台接收使用技巧？

### ISSUE THREAD

**Issue by user20161119** [alibaba/form-render#214]
请教一个问题，前端配置好动态表单后，后台如何接收这些字段？
```
{
  "schema": {
    "type": "object",
    "properties": {
      "string": {
        "title": "字符串",
        "type": "string"
      },
      "select": {
        "title": "单选",
        "type": "string",
        "enum": [
          "a",
          "b",
          "c"
        ],
        "enumNames": [
          "选项1",
          "选项2",
          "选项3"
        ]
      }
    }
  },
  "formData": {
    "string": "",
    "select": "a"
  }
}
```

比如要使用其中某一个字段的值进行后台更新操作，这样就没有了动态的特征了。一般这种动态表单前后端是怎么结合使用的？
比如我现在有一种使用场景：合同模板配置，前端动态配置好合同模板字段了，当用户提交表单的时候，需要将对应的字段去替换合同模板对应的占位符，生成合同的pdf,或者预览合同，暂时没有想到如何结合这个动态表单来做
拜谢

**Comment by siyi98** [comment]
**非bug问题请加入钉钉群聊进行讨论哈**
<img src="https://user-images.githubusercontent.com/29126094/98506573-c0cc8600-2296-11eb-92f2-e8623a7d14da.png" width="300"/>
