### ISSUE TITLE
[Feature]希望formRender的change函数可以暴露当前变化的组件name

### ISSUE THREAD

**Issue by QiannanXu** [alibaba/form-render#215]
### 期望的新功能

希望formRender的change函数可以暴露当前变化的组件name

### 为什么（简述一下使用场景）

复杂的表单可能会有一些数据或交互的联动，如果onChange函数中能够直接知道当前变化的组件，就可以避免对整个表单进行深层的遍历和比较。

目前onChange参数为formData，希望可以支持onChange(formData, name, value)，其中name表示当前输入的组件，value表示当前输入的组件值。

**Comment by siyi98** [comment]
@QiannanXu  没太明白你的意思，可以加钉钉群跟我们一起讨论一下？
<img  src="https://user-images.githubusercontent.com/29126094/98655807-dca95800-237a-11eb-9845-69e44ccbdc44.png" width="300"/>

**Comment by QiannanXu** [comment]
已加入。

**Comment by QiannanXu** [comment]
@siyi98  更新了一下描述。

**Comment by FateRiddle** [comment]
@QiannanXu onChange这个函数不是给用户拿来写回调的。你想象一下一个可控的input组件的有value和onChange两个props，onChange无外乎要写成
```js
const onChange = value => setValue(value)
```
只是用于同步state的，而不是你写各种callback处理逻辑的地方。要意识到这个onChange会递归的在所有的表单填写操作种执行，并不是你想象的一个纯顶层的api。

能简单描述一下你想在怎么样的场景下干什么事吗？我们好看看最优的解法，以及后续开放哪些合适的内部api。

**Comment by QiannanXu** [comment]
@FateRiddle 你好，我有一个比较复杂的schema，各种嵌套至少20多个字段，业务逻辑需要当某个深层的字段A发生变化的时候，字段B或者C会触发一些远程请求等特定需求

现在只能拿整个formData与变化之前的formData进行对比，希望有一个方式可以比较容易获取到当前是字段A还是其他字段变化，能够减少很多判断，也不用遍历整个formData。

**Comment by FateRiddle** [comment]
@QiannanXu sorry，回复迟了。正确解法是字段B C使用ui:widget属性，用自定义组件来完成这个需求。
注意自定义组件是能够拿到rootValue作为props的。rootValue里就能找到那个A字段的值，然后在自定义组件里自由写正常react的逻辑来完成服务端请求就行了。

还有啥问题可以再开哈~
