### ISSUE TITLE
[BUG]表单中插入a标签，点击后不会跳转

### ISSUE THREAD

**Issue by llb-27** [alibaba/form-render#218]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy?file=/src/index.js

**Comment by siyi98** [comment]
@llb-27 可以给个最小复现demo吗

**Comment by FateRiddle** [comment]
@llb-27 看一下你的a标签是否写对了。测试了下是没有问题的。
"link": {
        "title": "链接",
        "type": "html",
        "default": "<a href='https://www.taobao.com'>Link</a>"
      }
