### ISSUE TITLE
这项目不错 正是我需要的  ,  感谢 

### ISSUE THREAD

**Issue by 544751779** [alibaba/form-render#22]
老哥1.0版本什么时候上呢 ?

**Comment by tw93** [comment]
1.0 预计在外部使用至少1年后，再来升级大版本，同时大版本应该是有很好很大特性支持大家使用
目前form-render在阿里内部已经使用1年多啦，可以暂时不太关注1.0版本

还有后续issue建议只用于提交bug、或者好的点子，思考类的，关于咨询类的问题可以直接入群讨论
