### ISSUE TITLE
[BUG]list的分页数量选择无效-在fusion版本下

### ISSUE THREAD

**Issue by jiyeking** [alibaba/form-render#222]
搜索了之前的bug,#209 中类似，使用 `antd`就没事，在 `fusion`下， list在点击新增按钮后需要自己下拉到位置，然后超过10条的数据显示分页，点击下一页后，展示的10条list数据直接消失，再点击新增没有任何反应，打开日志模式，控制台打印有添加条目数据，我开始以为我环境的问题，各种测试修改页面样式，翻找官网配置，都没有解决，想到之前搭建了一个测试用的demo，然后测试了这个问题，展示操作都正常，然后修改这边的开发环境配置都修改的一样，还是有问题，最后发现是主题不一致，改成`antd`操作就正常了。😂，这里反馈一下，我先用 `antd`吧。。感觉 `fusion`不大稳。

**Comment by siyi98** [comment]
感谢反馈， @FateRiddle 看看这个问题

**Comment by 494279837** [comment]
@siyi98 @jiyeking 我也遇到了这个问题在0.9.11版本下，是还没修复么

**Comment by 494279837** [comment]
@FateRiddle
