### ISSUE TITLE
[Feature]Generator生成的schema，最终目的是想在移动端解析 展示表单的，有办法支持吗？

### ISSUE THREAD

**Issue by gaomeng965** [alibaba/form-render#227]
### 为什么（简述一下使用场景）

我的场景是，在PC端通过拖拽等配置操作，然后生成schema，最终作用到移动端，然后移动端解析这个schema，生成表单。
所以，有没有基于antd-mobile版本的Generator呢，
或者大佬帮给指个方向，感谢

**Comment by FateRiddle** [comment]
这个可以支持的，1.0版本开发进入尾声，在1.0版本支持。

**Comment by liucien** [comment]
@FateRiddle 请问下什么时候能够释出1.0版本支持移动端
