### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by XiaoColl** [alibaba/form-render#230]
### 期望的新功能。
单纯时分秒的区间选择 ，如下
"timerange": {
            "title": "time区间",
            "type": "range",
            "format": "time"
          },

### 为什么（简述一下使用场景）
选择 某时间段内进行查询

**Comment by FateRiddle** [comment]
"timeRange": {
            "title": "时间范围",
            "type": "range",
            "format": "time",
            "ui:options": {
              "placeholder": [
                "开始时间",
                "结束时间"
              ]
            }
          }
          
      已经支持了哈。
