### ISSUE TITLE
[BUG]Modal内的FormRender数组的一系列问题

### ISSUE THREAD

**Issue by mzl980425** [alibaba/form-render#231]
### 这个拖拽把手和边上的图标改成禁止划选好吗
![截屏2020-12-18 10 02 43](https://user-images.githubusercontent.com/22958600/102565323-34747500-4118-11eb-8de3-355c62f4d71f.png)

### 拖拽项被Modal挡住
![image](https://user-images.githubusercontent.com/22958600/102565545-a482fb00-4118-11eb-92ed-b803522a1279.png)

### 由于样式单位都是rem，导致大量空白区域
![image](https://user-images.githubusercontent.com/22958600/102565706-f4fa5880-4118-11eb-93e3-10a20e04d446.png)

**Comment by FateRiddle** [comment]
按钮可被选择的问题已经fix。rem可以尝试复位body的font-size
