### ISSUE TITLE
[BUG] 表单校验结果同步延迟

### ISSUE THREAD

**Issue by F-loat** [alibaba/form-render#232]
**1.依赖仓库的版本**：
- react：^16.8.6
- form-render：^0.9.1
- antd：^4.7.2

**2.问题描述**：

校验部分目前加了[防抖逻辑](https://github.com/alibaba/form-render/blob/master/src/hooks.js#L12-L20)，导致校验结果无法立即同步出来，而且无法通过 setTimeout 解决，建议直接增加一个 `validateData`  方法

``` js
const validateData = () => {
  const _data = outData || data;
  const _schema = outSchema || schema;
  return getValidateList(_data, _schema);
}

useImperativeHandle(forwardedRef, () => ({
  resetData,
  validateData,
}));
```

``` js
const valid = ref.current.validateData()
```

不知道目前这种校验 api 是出于什么考虑，更加符合 hooks 的风格嘛，感觉引入了一些不必要的逻辑

**3.最小复现demo**：

删掉 input 框内的文本后立马点击提交按钮，必填校验会失效，弹出表单数据

这个问题会导致用户可以低成本地跳过表单校验，希望能尽快修复

https://codesandbox.io/s/form-render-validate-bug-kzi1e

![image](https://user-images.githubusercontent.com/16759376/102568518-9b952800-411e-11eb-8d22-e583429ee6ab.png)

**Comment by F-loat** [comment]
通过 `setTimeout` 可以暂时规避这个问题的，之前的使用方式有误

``` js
const [valid, setValid] = useState<string[]>([]);
const [showValidate, setShowValidate] = useState<boolean>(false);
const validRef = useRef(valid);

validRef.current = valid;

const handleSubmit = () => {
  setShowValidate(true);
  setTimeout(() => {
    if (validRef.current.length > 0) {
      onInvalid(validRef.current);
      return;
    }
    onSubmit(formData);
    setShowValidate(false);
  }, 600);
};
```

**Comment by FateRiddle** [comment]
去掉了校验的异步，发现校验不是性能瓶颈。写 FR 1.0 的时候引入了 isEditing 的模式，在 isEditing = true下使用“状态快照”，等 isEditing = false 后再进行计算，提高使用性能。
