### ISSUE TITLE
[BUG]schema经过cloneDeep以后页面卡死

### ISSUE THREAD

**Issue by mzl980425** [alibaba/form-render#233]
**1.依赖仓库的版本**：
"react": "17.0.0",
"react-dom": "17.0.0",
"react-scripts": "3.4.3",
"antd": "^4.4.1",
"form-render": "^0.9.0",
"lodash": "^4.17.11"

**2.问题描述**：schema经过cloneDeep以后会导致FormRender频繁setState
![image](https://user-images.githubusercontent.com/22958600/102734629-43a72d00-437b-11eb-87d5-45d963f1152a.png)

**3.最小复现demo**：https://codesandbox.io/s/vibrant-architecture-58xft?file=/src/App.js

**Comment by FateRiddle** [comment]
pattern: /^http.*/,
message: "请填写以http开头的入口地址"

代码里出现了regex。需要写成string。pattern: /^http.*/  变成  pattern: "^http.*"
这个修改了之后，你的例子就ok了。
