### ISSUE TITLE
[BUG]debouncedValidate is not a function

### ISSUE THREAD

**Issue by kuangyuliang** [alibaba/form-render#234]
**1.依赖仓库的版本**：
- react：16.12.0
- form-render：0.9.2
- antd：4.9.4

**2.问题描述**：
请看demo，直接使用是没问题，但是放到useEffect里面，就报debouncedValidate is not a function

**3.最小复现demo**：
https://codesandbox.io/s/cranky-tharp-hhcf3?file=/src/App.tsx

**Comment by FateRiddle** [comment]
钉钉讨论了下，是hooks使用的问题。

**Comment by qq5050595531** [comment]
遇到同样的问题，我这是放到弹窗不行
