### ISSUE TITLE
[BUG] 列表组件不受控

### ISSUE THREAD

**Issue by F-loat** [alibaba/form-render#244]
**1.依赖仓库的版本**：
- react：17.0.0
- form-render：0.9.8
- antd：4.10.3

**2.问题描述**：

列表组件不受控，可通过 FormRender 不设置 onChange 方法来复现，表现为列表项无法新增，但可以删除

**3.最小复现demo**：

https://codesandbox.io/s/form-render-array-issue-is8zu?file=/src/App.js

**Comment by FateRiddle** [comment]
这个不算bug吧。form-render现在的设计模式就是可控组件，所以必须设定onChange。否则state是不会改变的，如果有UI的变化也只是表象的。没有onChange这个FR的表单没法正常运行和输出数据吧。

**Comment by F-loat** [comment]
无法新增是正常的，但是可以删除不正常
