### ISSUE TITLE
[BUG]使用snowpack脚手架的项目中无法正常使用form-render

### ISSUE THREAD

**Issue by hotpotwang** [alibaba/form-render#245]
**1.依赖仓库的版本**：
- react：^17.0.0
- form-render：^0.9.8
- antd：^4.10.3
- funsion（如果用的是fusion）：

**2.问题描述**：
使用snowpack脚手架npx create-snowpack-app react-snowpack --template @snowpack/app-template-react-typescript构建的项目中使用form-render时无法正常渲染，会报该错误：
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `ForwardRef(InternalSelect)`.
**3.最小复现demo**：
 https://github.com/hotpotwang/snowpackErr/tree/master

https://codesandbox.io/s/form-renderjichudemo-f55oy
email：464984407@qq.com

**Comment by FateRiddle** [comment]
能请问一下，antd支持么？我记得很多npm包都不支持esm吧？这个问题大概会一直存在吧，使用snowpack来开发是否需要考虑一下解决不仅仅是FR这一侧的问题吧？

**Comment by suanmei** [comment]
antd 支持 esm 的，form-render 只需要把 esmodule 的 build 时的 babel-plugin-import 规则稍微改一下就行

```
(name: string): string => `antd/es/${name}/style/index.js`
```

**Comment by suanmei** [comment]
form render 急用，万望兄弟紧急发一版
