### ISSUE TITLE
[BUG]fusion时间范围组件不能选择

### ISSUE THREAD

**Issue by Copyes** [alibaba/form-render#251]
**1.依赖仓库的版本**：
- react：16.3.0
- form-render：0.9.8
- funsion：是

**2.问题描述**：
使用fr-generator 1.0.1版本生成的schema中时间范围组件渲染后，无法选择时间范围；
**3.最小复现demo**：
https://codesandbox.io/s/zidingyizujian-forked-zqcb0?file=/src/index.js

**Comment by FateRiddle** [comment]
0.9.11 fix
