### ISSUE TITLE
[Feature] add support for getCalendarContainer prop to rc-color-picker 

### ISSUE THREAD

**Issue by wlx200510** [alibaba/form-render#252]
### 期望的新功能
希望能设置 rc-color-picker 的 gerCalendarContainer 属性
### 为什么（简述一下使用场景）
类似 configProvider 中的 getPopupContainer 做的事，不希望color-picker 插入到body 节点
但看了下源码没有透传相关参数

**Comment by wlx200510** [comment]
我想提个pr，让这个getCalendarContainer属性直接同步 configProvider 中的 gerPopupContainer 配置，不知道是否合适？

**Comment by wlx200510** [comment]
react-sortable-hoc has the same question lack setting for helperContainer

**Comment by wlx200510** [comment]
另一种思路是 针对 colorPicker 和 react-sortable-hoc 各自在form-render上支持传入自定义属性，然后优先级最高，通过 {...props} 传入到对应组件的jsx上，其他的都是antd的，用configProvider 即可

**Comment by FateRiddle** [comment]
看了你的pr，这样一个个属性补充的玩法会乱。
我的做法是，所有widget中包含两个组件的单元格，都会分别开放两个props属性。例如color组件会开放
'props', 'pickerProps', 这样所有文档上的props都可以透传使用了。本周发form-render 1.0 版本。
