### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yardfarmer** [alibaba/form-render#255]
**2.问题描述**：
List  widget 无法新增 List Item。详见 playground 示例。

**3.最小复现demo**：
https://x-render.gitee.io/schema-generator/playground

**Comment by FateRiddle** [comment]
这个不是form-render的issue哈，在对应的https://github.com/form-render/schema-generator 仓库提。
而且就是个纯展示，要是在拖拽搭建上实现list的结构，代码实现成本太高了。
