### ISSUE TITLE
[BUG] webpack5 中 use-debounce 的 import 方式问题

### ISSUE THREAD

**Issue by stickmy** [alibaba/form-render#257]
**1.依赖仓库的版本**：
- react：
- form-render： latest
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：
webpack5 支持了 exports field in package.json（<https://github.com/webpack/webpack/issues/9509>）
`use-debounce` 的 package.json 中仅仅 exports 了 main entry

```js
"exports": {
    "./package.json": "./package.json",
    ".": {
      "import": "./esm/index.js",
      "require": "./lib/index.js"
    }
}
```

导致在 webpack5 中使用 form-render 报错

```js
Module not found: Error: Package path ./lib/useDebouncedCallback is not exported from package /Users/xxx/test-workspace/node_modules/use-debounce (see exports field in /Users/xxx/test-workspace/node_modules/use-debounce/package.json)
```

修复方案：
1. 改变 import 使用方法
2. 给 use-debounce 提 feature，支持 sub path import (<https://github.com/webpack/webpack/issues/9509#issuecomment-599770169>)

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by FateRiddle** [comment]
请教一下 @stickmy 如果use-debounce那边不动，我这边有直接处理方式么？

**Comment by FateRiddle** [comment]
已经修复。我直接内置了use-debounce

**Comment by simplast** [comment]
> 已经修复。我直接内置了use-debounce

请问下你内置的是哪个版本的
