### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by 2534290808** [alibaba/form-render#266]
### 为什么（简述一下使用场景）
为什么不用antd里的Form和Form.Item以及Form.List进行重构，这个解决了验证问题，由于Form是增量更新的，也解决了更新的问题 😄

**Comment by FateRiddle** [comment]
重构在做啊。但是完全用antd的form，一些复杂的ui目前antd还没有给出好的解法（非常复杂的list展示）
校验的问题，新增了validator字段，已经可以动态校验了。
