### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by PathFun** [alibaba/form-render#268]
### 期望的新功能
  联动的hidden只是在UI层面上的隐藏，数据并没有改变， 希望可以新增一个可以删除数据的， 或者把数据修改成false
### 为什么（简述一下使用场景）
 很多配置项首先是判断有没有此配置项才能去配置它，例如配置G2的图表时，legend有可能的可能值有true， false， {}

**Comment by PathFun** [comment]
在自定义一个object组件时，往往会报错， 能不能出一个自定义object组件的例子

**Comment by FateRiddle** [comment]
数据上删除的事儿需要在submit处完成。现在版本的FormRender由于状态是完全外置的，所以没有表单提交的收束控制。大版本上来之后就ok了。现在submit无法收束到FR管控，而是用户随时拿着formData去做，所以建议目前先在submit的地方自行处理一下。
