### ISSUE TITLE
[BUG] 自定义组件 onChange 一个对象无效

### ISSUE THREAD

**Issue by alvin0216** [alibaba/form-render#269]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：

```js
const schema = {
  type: 'object',
  properties: {
    demo: {
      title: '字符串',
      'ui:widget': 'cascade',
    },
  },
};
```

想要的效果

```js
onChange(name, { a:1, b: [{ name: 1}] })
```

希望得到的是对象，请问如何实现

**3.最小复现demo**：

https://codesandbox.io/s/zidingyizujian-forked-xcfll?file=/src/Cascade.js

**Comment by alvin0216** [comment]
### 如图，onChange 成功后 props value 并未更新
![image](https://user-images.githubusercontent.com/34113677/111060062-3bbbdc80-84d5-11eb-80c5-9ba4d53a13f3.png)

**Comment by makmav** [comment]
#265 试试这个
onchange(null, null, data) 你的demo里onchange的第一个参数去了

**Comment by alvin0216** [comment]
> #265

嗯 在 codebox 上是可以的，但是本身我这边的代码是存在问题的，但我返回一个新对象去 onChange 时，打印是成功的，但是返回自定义组件的 props 是没有更新的，如上图。


我的解决方式：直接改 props.value 的引用，比如 `props.value.list = [xxxx]` ，然后在 onChange 解决了上面这个问题

**Comment by FateRiddle** [comment]
如 @makmav 的建议。onChange只改本widget的值，如果要改上层，使用第三个参数。我先关了哈
