### ISSUE TITLE
关于组件联动扩展的思路

### ISSUE THREAD

**Issue by crissii** [alibaba/form-render#27]
现有的联动功能还是有点单薄，无法满足复杂业务的需求。例如：选择某个组件的值后，各种可能的变化，比如更改默认值（身份证输入后，默认输入性别，出生日期等），必填，更改校验规则，更改显示隐藏（目前来说支持），无法避免通过编码的方式来实现定制化需求。
来说说我们之前是怎么实现，看看能不能有些不一样的碰撞。整体思路就是通过编码回调的方式，让使用者自己插入代码。
使用方式：
![image](https://user-images.githubusercontent.com/4486590/69506992-e704f300-0f6b-11ea-8af1-38940685f279.png)
每个表单我们定义了一个方案Key,你项目中可以在如下目录进行扩展，
![image](https://user-images.githubusercontent.com/4486590/69507032-11ef4700-0f6c-11ea-987c-f77ca61f33a8.png)
在默认实现中采用了高阶函数，去扫描项目下的目录，如果有实现则采用项目下的文件。
![image](https://user-images.githubusercontent.com/4486590/69507092-495df380-0f6c-11ea-9d18-912d857e0552.png)
blockWrapper的主要实现：
![image](https://user-images.githubusercontent.com/4486590/69507151-7f02dc80-0f6c-11ea-8213-18d1236da447.png)
![image](https://user-images.githubusercontent.com/4486590/69507179-90e47f80-0f6c-11ea-8fd7-7932503a86de.png)
大致流程就是扫描项目下的文件，如果有覆盖就用覆盖后的文件，没有覆盖则使用默认实现。
然后在add_main提供了一些可以扩展的回调函数，供具体的方案去扩展。
例如ready()表单加载完后的方法等等

**Comment by FateRiddle** [comment]
@crissii 抱歉回复迟了。刚提出就看了，非常感动你不仅提出了问题还给了可能的解法。感觉没有深入思考后回复可能会草率所以没有在第一时间给你个答复。

联动的问题光一个ui:hidden确实覆盖不了，fr现在内部支持的业务也有很多这方面诉求。参考各个方案，确实需要给用户写函数的自由度才能从根本上解决联动，我们给出的解法是支持schema字段的函数表达式化。破坏性小，不引入新的api，初学者友好。

不知道你是否满意？

pub/sub模型，如果整合到fr后，可能的结构是开一些生命周期类的方法，然后在里面写所有的listener。这个对于使用者的学习负担有点大。简洁易用是 formrender 和现行一些其他表单解决方案对比的一大优势，我们最希望避免的就是在支持高端应用的同时引入过多配置和api，把负担转交给了新上手或者只需要简单场景的使用者。

**Comment by crissii** [comment]
很期待你们关于联动这块的方案出来，我们之前做的那套系统是解决单表的crud的轻代码方案，前后端功能都有，关于前端我们也一直思考好的解决方案，现有这套灵活度太高，甚至可以完全重写render方法，版本升级后，会带来很多不兼容，目前我们可能思维定势，没有找到更好解决方式，也期待看到你们解决方案，互相借鉴，.



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FateRiddle <notifications@github.com&gt;
发送时间: 2019年11月30日 11:49
收件人: alibaba/form-render <form-render@noreply.github.com&gt;
抄送: crissii <58562503@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/form-render] 关于组件联动扩展的思路 (#27)




@crissii 抱歉回复迟了。刚提出就看了，非常感动你不仅提出了问题还给了可能的解法。感觉没有深入思考后回复可能会草率所以没有在第一时间给你个答复。
 
联动的问题光一个ui:hidden确实覆盖不了，fr现在内部支持的业务也有很多这方面诉求。参考各个方案，确实需要给用户写函数的自由度才能从根本上解决联动，我们给出的解法是支持schema字段的函数表达式化。破坏性小，不引入新的api，初学者友好。
 
不知道你是否满意？
 
pub/sub模型，如果整合到fr后，可能的结构是开一些生命周期类的方法，然后在里面写所有的listener。这个对于使用者的学习负担有点大。简洁易用是 formrender 和现行一些其他表单解决方案对比的一大优势，我们最希望避免的就是在支持高端应用的同时引入过多配置和api，把负担转交给了新上手或者只需要简单场景的使用者。

**Comment by FateRiddle** [comment]
@crissii 目前已经支持联动了哦，可以参考文档[如何联动](https://alibaba.github.io/form-render/#/docs/function)部分。有什么建议欢迎再聊，先关了哦。
