### ISSUE TITLE
ant 主题无法生效

### ISSUE THREAD

**Issue by Baoyx007** [alibaba/form-render#272]
https://github.com/alibaba/form-render/blob/cfb5f8f5a85406097edaabc5b01b001d7c6379b1/packages/form-render/.fatherrc.js#L18

https://ant.design/docs/react/customize-theme-cn:
如果你在使用 babel-plugin-import 的 style 配置来引入样式，需要将配置值从 'css' 改为 true，这样会引入 less 文件。

**Comment by FateRiddle** [comment]
收到，谢谢！

**Comment by FateRiddle** [comment]
已经改了，fixed。
