### ISSUE TITLE
[BUG]fusion 主题下，array的自动翻页无法触发翻页操作

### ISSUE THREAD

**Issue by xiaosong** [alibaba/form-render#274]
**1.依赖仓库的版本**：
- react：^16.4.1
- form-render：0.10.0
- antd：无
- funsion（如果用的是fusion）：^1.x

**2.问题描述**：
array 类型的翻页功能无法翻页

**Comment by FateRiddle** [comment]
![image](https://user-images.githubusercontent.com/12005259/112115331-05c4d980-8bf4-11eb-8a1a-87e279b9333c.png)

**Comment by FateRiddle** [comment]
fixed
