### ISSUE TITLE
[BUG]数组类型中数组项拖拽时数组项样式丢失

### ISSUE THREAD

**Issue by xiaosong** [alibaba/form-render#278]
**1.依赖仓库的版本**：
- react：16.4.1
- form-render：0.10.x
- antd：无
- funsion（如果用的是fusion）：1.x

**2.问题描述**：

拖拽数组项时，数组项样式丢失

**3.最小复现demo**：

https://codesandbox.io/s/form-renderjichudemo-f55oy

**Comment by FateRiddle** [comment]
form-render 1.0版本这个问题会解决，本周发版
