### ISSUE TITLE
[BUG] TextArea 字数限制不生效

### ISSUE THREAD

**Issue by alvin0216** [alibaba/form-render#280]
**1.依赖仓库的版本**：
- react：
- form-render：
- antd：
- funsion（如果用的是fusion）：

**2.问题描述**：

**3.最小复现demo**：

如图，官网 playground 上的例子

![image](https://user-images.githubusercontent.com/34113677/112589494-2aab8d80-8e3c-11eb-9f72-3f3eb809030d.png)

**Comment by alvin0216** [comment]
目前解决可行方案 通过 'ui:options' 强制透传 props

**Comment by FateRiddle** [comment]
本周form-render 1.0 版本会出。之后建议的行为，就是使用antd的原生props（就如你写的透传解决方案）
