### ISSUE TITLE
[BUG]当 descIcon 显示时，悬浮的描述控件会被遮盖

### ISSUE THREAD

**Issue by seasonyuu** [alibaba/form-render#290]
**1.依赖仓库的版本**：
- react：17.0.1
- form-render：0.10.5
- antd：4.14.0
- funsion（如果用的是fusion）：

**2.问题描述**：

配置 `showDescIcon` 为 `true`，而后当 `description` 文本较长时，会分为多行，此时顶部就会被遮盖了。

**3.最小复现demo**：

playground 中即可直接复现

<img width="712" alt="Snipaste_2021-04-01_14-56-39" src="https://user-images.githubusercontent.com/8638535/113255779-d18ba000-92fa-11eb-810f-938b4c97d342.png">

**Comment by FateRiddle** [comment]
这个只是在playground里遮住了吧，正式使用是没有问题的。

**Comment by seasonyuu** [comment]
正式使用也有问题。。。。。我只是提供个复现路径说 playground 就可以看到。。。你怎么就给 close 了

**Comment by seasonyuu** [comment]
Related to: https://github.com/alibaba/form-render/issues/291
