### ISSUE TITLE
[BUG] where the "form-render/lib/antd"?

### ISSUE THREAD

**Issue by caimingyi484** [alibaba/form-render#295]
cannot resolve module form-render/lib/antd from F:\www\form-render\docs\index.md
Can't resolve 'form-render/lib/antd' in 'F:\www\form-render\docs'
Error: Can't resolve 'form-render/lib/antd' in 'F:\www\form-render\docs'.....

**Comment by F-loat** [comment]
Please execute `yarn build` first.

**Comment by caimingyi484** [comment]
> Please execute `yarn build` first.

Ok, Thanks!
