### ISSUE TITLE
[BUG] 1.0.0-beta.2 版本，输入过快，数据不正确

### ISSUE THREAD

**Issue by kala888** [alibaba/form-render#298]
**1.依赖仓库的版本**：
   "antd": "^4.14.0",
    "form-render": "1.0.0-beta.2",
    "rc-util": "5.9.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0",
    "@alifd/next": "^1.x"

**2.问题描述**：
在页面地址，快速输入123，立马切换到，下面textarea，输入123，
页面地址的123输入会变化

**3.最小复现demo**：
 https://codesandbox.io/s/fr-fast-input-issue-ri0z4

https://user-images.githubusercontent.com/1215976/114510199-f7a13080-9c68-11eb-8fcb-9931a5b4c3f3.mp4

**Comment by FateRiddle** [comment]
这个问题在1.0.1已经fix了。谢谢！
