### ISSUE TITLE
[BUG] 1.0.0-beta.2 与antd的Modal配合，getDefaultList报错Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by kala888** [alibaba/form-render#299]
默认Modal的 visible=false时，初始化报错

**1.依赖仓库的版本**：
    "antd": "^4.14.0",
    "form-render": "1.0.0-beta.2",
    "rc-util": "5.9.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0"

**2.问题描述**：

**3.最小复现demo**：
https://codesandbox.io/s/fr-popup-issue-qrw75?file=/src/App.tsx

**Comment by kala888** [comment]
经过测试，临时添加
 const form = useForm()
  form.syncStuff({ flatten: {} })
可以绕过这个bug

**Comment by FateRiddle** [comment]
升级了1.0.1 不会报错了，但是schema本身没有写对
```js
const theForm = {
  schema: {
    type: "string",
    title: "测试"
  }
};
```
正常的外面还有一层object哦
```js
const schema = {
  type: 'object',
  properties: {
    input1: {
      title: '简单输入框',
      type: 'string',
      required: true,
    },
    input1: {
      title: '简单输入框',
      type: 'boolean',
      required: true,
    },
    input2: {
      title: '简单输入框2',
      type: 'string',
      required: true,
    },
  },
};
```
升级了1.0.1，也不会报错了。
