### ISSUE TITLE
Vue项目里如何调用？

### ISSUE THREAD

**Issue by wangyuhaoa** [alibaba/form-render#30]
最好有个小demo

**Comment by FateRiddle** [comment]
目前不支持。有个远期接入的打算。主要原因是说到底fr是个react组件，除了核心逻辑重用以外需要重写渲染层。支持vue应该会开个分立的项目。短期（1-2个月）内fr有很多高优先级的事儿，包括功能优化扩展、上游schema可视化生成等。需要等待~ 欢迎加入我们钉钉群，每次大更新会通知各位。
