### ISSUE TITLE
[BUG] 1.0.0-beta.2 radio（string + enum）校验问题

### ISSUE THREAD

**Issue by kala888** [alibaba/form-render#300]
两个字段，设置required为true，某种情况下，radio选择后，没有设置数

**1.依赖仓库的版本**：
  "antd": "^4.14.0",
    "form-render": "1.0.0-beta.2",
    "rc-util": "5.9.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0"

**2.问题描述**：
1. 直接点击”测试“
2. 名称输入123
3. 点击”测试“
4. 选择类型
5. 点击”测试“

期望：点击第5步测试的时候，正确校验数据

![image](https://user-images.githubusercontent.com/1215976/114512858-22d94f00-9c6c-11eb-872e-19eec0ec0d3b.png)

tips: 第六步，如果再名称再次添加append两个字符，校验就正确了

**3.最小复现demo**：
https://codesandbox.io/s/fr-validation-issue-mp04y?file=/package.json:145-303

**Comment by FateRiddle** [comment]
非常感谢！form-render组件上有一个debug的props，测试可以直接用debug=true来看哦。
我升级到最新，按你的步骤点了，看来都是正常，应该fix了，先关了哈。
