### ISSUE TITLE
[Feature]1.0是否将antd作为了强依赖，还有没有保留原先纯粹的表单核心包，然后通过自定义组件注册第三方组件库的能力

### ISSUE THREAD

**Issue by liucien** [alibaba/form-render#301]
### 期望的新功能
原先是可以通过 `import FormRender from 'form-render';` 的方式直接使用表单能力，将form-render作为表单控制器[#112](https://github.com/alibaba/form-render/issues/112)，组件全部由外部注入
![image](https://user-images.githubusercontent.com/32785166/114644466-258a8180-9d0a-11eb-90f3-057c32eba19e.png)

但是现在我看antd已经是写死在[源码](https://github.com/alibaba/form-render/blob/51cbe09c3a/packages/FR1.0/src/index.js)之中了，还有这种不依赖antd只作为一个纯粹的表单控制器的能力么

### 为什么（简述一下使用场景）
公司内部组件，并不依赖antd，只想使用表单配置与控制能力

**Comment by FateRiddle** [comment]
FormRender 1.0 与之前一样，对组件库的口子都是开着的，外部使用可以通过 widgets & mapping 两个 props 注入，内部可以也可以方便的提 pr。对 antd 的依赖是 peerdependency，form-render 本身还是纯净的，只是写了非常薄一层对 antd 组件的 wrapper，没有必要特地分出去。之后组件库接入也是同样模式：wrapper 直接内置于核心代码，组件库本身 peerdependency。

**Comment by liucien** [comment]
@FateRiddle 那原先`import FormRender from 'form-render'`这种方式肯定是不行了，新的入口是直接引入[FR](https://github.com/alibaba/form-render/blob/51cbe09c3a9301a3449c095d84f0967fd17417f1/packages/FR1.0/src/FR/index.js)，然后直接拷贝[index](https://github.com/alibaba/form-render/blob/master/packages/FR1.0/src/index.js)，本地重新封装一层么😂？还有即使是peerdependency依赖，还是会去找antd的，直接就报错了，而且即使是核心包里面也没法确定有没有用到antd的组件吧，就像description这个属性应该用的是antd的Popover之类的组件吧，如果说像官网说的作为下一代React表单解决方案也应该不该直接内置antd吧😁
![image](https://user-images.githubusercontent.com/32785166/114647959-8a48da80-9d10-11eb-8721-e48147642857.png)
