### ISSUE TITLE
[Feature]关于label的规范

### ISSUE THREAD

**Issue by crissii** [alibaba/form-render#31]
antd的设计规范里头，关于表单对齐规范：
![image](https://user-images.githubusercontent.com/4486590/70028454-ae09f580-15df-11ea-8401-5875e1c70e8e.png)
而本系统的是：
![image](https://user-images.githubusercontent.com/4486590/70028491-c417b600-15df-11ea-95e9-a4328d6d25d2.png)

**Comment by FateRiddle** [comment]
谢谢。@crissii 目前可以使用样式覆盖, 对fr-label标签进行覆盖。参见文档[样式覆盖](https://alibaba.github.io/form-render/#/docs/css)
![image](https://user-images.githubusercontent.com/12005259/70137046-17fdca00-16c8-11ea-8e27-23932d70d63b.png)
下个版本label打算接入antd的视觉规范，使用12的grid，并开放全局和单体参数。

**Comment by tw93** [comment]
@FateRiddle 对于横排的场景，样式全部是这样就好，不要让用户手动去改样式了

**Comment by FateRiddle** [comment]
最新版本，label已经按规范展示了哦~
