### ISSUE TITLE
time格式的时间设置默认值无法在组件里面渲染

### ISSUE THREAD

**Issue by philousWen** [alibaba/form-render#32]
time格式的时间设置默认值无法再次在组件里面渲染

![image](https://user-images.githubusercontent.com/7477751/70120130-c3962280-16a6-11ea-8b75-65864aac5334.png)

JSON Schema如下：
{
  "propsSchema": {
    "type": "object",
    "properties": {
      "string": {
        "title": "字符串",
        "type": "string"
      },
      "time": {
        "title": "时间（时分秒)",
        "type": "string",
        "format": "time"
      }
    }
  },
  "formData": {
    "string": "23",
    "time": "11:56:58"
  }
}

**Comment by FateRiddle** [comment]
已经修复。见https://github.com/alibaba/form-render/blob/master/CHANGELOG.md
