### ISSUE TITLE
[Feature] array 中可以控制添加按钮的显隐

### ISSUE THREAD

**Issue by lengthmin** [alibaba/form-render#34]
**Is your feature request related to a problem? Please describe.**
现在我有个功能需求是比赛报名，但是比赛报名不能超过三人，所以希望添加按钮超过三人可以隐藏，看代码发现目前没办法控制显隐。

https://github.com/alibaba/form-render/blob/master/src/widgets/antd/list.jsx#L133

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/13938334/70374041-8f7e6400-1929-11ea-9500-c0c5918acef1.png)
希望可以控制图示这个按钮的显隐。

**Describe alternatives you've considered**

**Additional context**

**Comment by FateRiddle** [comment]
@lengthmin 最新版支持ui:readonly 参数为 true 时，列表所有的可控操作都会消失。可以试试看哦~

**Comment by lengthmin** [comment]
那想删除岂不是不行了，只希望能控制这个添加的消失...

**Comment by FateRiddle** [comment]
@lengthmin 我理解错了。你的建议是合理的。已经在开发中。

**Comment by lengthmin** [comment]
> @lengthmin 我理解错了。你的建议是合理的。已经在开发中。

谢啦~
还有类推的操作就是：
- 默认展示 minNum 个数组,
- minNum 个数组时隐藏删除按钮...

希望可以考虑一下~

**Comment by lengthmin** [comment]
如果不默认实现隐藏删除按钮的话，还希望有个参数能控制删除按钮...
用起来像 "ui:hiddenDeleteButton": "num === 1"

**Comment by FateRiddle** [comment]
@lengthmin 这个的场景是什么？可以通过校验来判断数据的有效性。并没有禁止删除，因为考虑到有人希望删除特定的一条，然后在新增一条补回，不应该禁止此类操作。

**Comment by lengthmin** [comment]
@FateRiddle 你说的有道理，通过校验来判断就可以了。
我一开始这样想是因为 想让用户**明显的感觉到有最低最高条目的限制**。
