### ISSUE TITLE
[Bug]  Code Sandbox 运行报错

### ISSUE THREAD

**Issue by beimuaihui** [alibaba/form-render#41]
yarn add form-render 也是报错，提示descriptionList找不到；大小写有问题

**Comment by lengthmin** [comment]
![image](https://user-images.githubusercontent.com/13938334/70720821-7d3c6580-1d2f-11ea-949a-862925c4d6b8.png)
同样遇到

**Comment by FateRiddle** [comment]
很抱歉发生了这种问题。在0.4.3版本已经解决了。原因是macOS系统不区分文件大小写，所以本地虽然看着改了名，实际无效。
