### ISSUE TITLE
[Feature] TypeScript definitions

### ISSUE THREAD

**Issue by ddzsy** [alibaba/form-render#44]
Need typescript definitions when use form-render in typescript projects

**Comment by FateRiddle** [comment]
We are working on it.

**Comment by FateRiddle** [comment]
参考文档[如何在ts项目中使用form-render](https://alibaba.github.io/form-render/#/docs/typescript)  ，其中有codesandbox的完整样例。基本上就是添加一个 index.d.ts文件。
form-render会在后续版本自动支持ts，请期待。
