### ISSUE TITLE
颜色组件输入框验证问题

### ISSUE THREAD

**Issue by philousWen** [alibaba/form-render#48]
颜色组件输入框内，输入16进制颜色，不带”#“时，颜色组件能正常渲染，未提示颜色输入值不合法；但是最终拿到的颜色数据没有”#“导致在浏览器内渲染颜色失败
![image](https://user-images.githubusercontent.com/7477751/71431464-f616c680-270c-11ea-9cbe-ab6ebf03888f.png)

**Comment by FateRiddle** [comment]
已解决 v0.4.4
