### ISSUE TITLE
[Bug]代码拉取后无法启动

### ISSUE THREAD

**Issue by liucien** [alibaba/form-render#49]
##### 2.实际的效果以及期待效果或功能说明 
node.js版本 12.0.0
请问下是不支持windows下开发么，12.0.0版本下运行就报错，12.x版本以下可以启动不报错但是9000端口访问不到任何东西

 - 实际的效果：
图片上传一直失败，直接贴信息了
PS D:\test\form-render> npm run start

> form-render@0.4.4 start D:\test\form-render
> npm run watch & webpack-dev-server --open

> form-render@0.4.4 watch D:\test\form-render
> webpack --watch

webpack is watching the files…

#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0000003AE9BFD2C0npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! form-render@0.4.4 watch: `webpack --watch`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the form-render@0.4.4 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\14814\AppData\Roaming\npm-cache\_logs\2019-12-25T15_54_32_911Z-debug.log
i ｢wds｣: Project is running at http://127.0.0.1:9000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\test\form-render\docs\demo
i ｢wdm｣: wait until bundle finished: /

#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0000005122EFD930npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! form-render@0.4.4 start: `npm run watch & webpack-dev-server --open`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the form-render@0.4.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
![Uploading E91D0A60-0B54-4362-A38F-9B77ED296C2A.png…]()

 - 期待的效果或功能：
能够正常启动开发

**Comment by liucien** [comment]
将 npm run watch 去掉就行
![image](https://user-images.githubusercontent.com/32785166/71615047-22898180-2bea-11ea-9edd-995b6dd8a178.png)

**Comment by FateRiddle** [comment]
@liucien 收到。
