### ISSUE TITLE
[Q]日期控件&formLayout&数字允许为空

### ISSUE THREAD

**Issue by phoema** [alibaba/form-render#51]
1、请问日期控件是用的什么？我如何统一设置为使用antd默认的moment组件？
2、关于lable宽度，我如何使用antd中的formLayout属性进行替代？

**Comment by phoema** [comment]
3、示例代码里，numberDemo并没有设置required，为什么他也是必填项？
4、通过formRender打开的页面，为什么会直接执行Validate，每个字段都出现提示？我希望在表单新建，保存按钮点击之前不出现提示。

**Comment by JLoveI** [comment]
同样的问题

**Comment by FateRiddle** [comment]
1. [Demo](https://alibaba.github.io/form-render/docs/demo/index.html) 中有各种时间的例子
2. 不能。考虑到fr中不同控件可以设置不同长度的布局，使用antd的百分比布局在很多情况并不美观。现在可以通过labelWidth字段设置全局label宽度，之后还会允许单个、局部的修改。
3. 你的场景可以使用普通的input框使用pattern来写自定义的正则规则。或者给个默认值(default) 0。数据类型的校验是必须的，也是90%的使用者的需求，不校验会带来更多问题。
4. 这个需求在处理中。

**Comment by phoema** [comment]
收到，辛苦了。
