### ISSUE TITLE
[Q]问一个排序的问题

### ISSUE THREAD

**Issue by liucien** [alibaba/form-render#53]
感觉可以开一个专门提问的标签，看了一晚上实在是没明白，求指点 T_T
![image](https://user-images.githubusercontent.com/32785166/71831387-c344d900-30e3-11ea-8189-611e6631b6d9.png)

**Comment by liucien** [comment]
发现是用Object.keys进行位置排列，那我想要动态去拖拽改变位置，然后在重新生成一份JSON Schema，该怎么保证object的内属性的位置呢

**Comment by FateRiddle** [comment]
目前各个项目中使用的情况看，排序都是会按照propsSchema定义的顺序展示formData的。你可以试试。如果出现排序混乱的问题可以重开这个issue反映哦~
