### ISSUE TITLE
[Feature]Required 字段能否移动到propsSchema字段属性上

### ISSUE THREAD

**Issue by JLoveI** [alibaba/form-render#54]

**Comment by FateRiddle** [comment]
可以说的详细一点哦。现在的样子，期望的样子，为啥有这个需求等等。方便我们更好的回复哦~

另外，schema字段的定义是参考 JSON schema 的国际规范的。

**Comment by JLoveI** [comment]
Require也属于字段的验证和schema在一起更方便管理，有些场景把require放在外面会出现没有字段ui:hidden =true（建议加一个ui:visible） 的情况下出现需要字段验证而无法提交.
