### ISSUE TITLE
[Feature] 表单类型缺失

### ISSUE THREAD

**Issue by xiaohuangmao** [alibaba/form-render#55]
表单类型type的值目前不支持button按钮吗，这不应该吧。一个表单中包含上传/导入/导出按钮是比较常见的需求啊。如果这都要开发自定义组件的话，会令我感觉很沮丧。

**Comment by FateRiddle** [comment]
关于按钮。
1. 最简单的解法是：按钮在布局上往往并不属于表单。可以放在form-render外处理，如导入导出，很多都是放在表单上方的。
2. 不支持button的原因：按钮一般带有强业务逻辑，在UI排版上也会根据需求各不相同。提供一个全能的按钮控件并不太现实。最好的做法就是写自定义组件去写表单逻辑。
3. 我觉得后续可以提供一些常用自定义组件的写法模板，减少这方面的学习代价。
