### ISSUE TITLE
[Bug] type值为array的时候 配置的buttons按钮组会默认出现一个新增按钮

### ISSUE THREAD

**Issue by xiaohuangmao** [alibaba/form-render#56]
type值为array的时候 配置的buttons按钮组会默认出现一个新增按钮，有时候我们并不需要这个新增按钮怎么处理？

**Comment by FateRiddle** [comment]
https://alibaba.github.io/form-render/#/docs/ui-schema?id=%e6%8e%a7%e5%88%b6%e8%a1%a8%e5%8d%95%e9%a1%b9%e7%9a%84-ui-%e5%b1%95%e7%a4%ba%ef%bc%88%e5%85%b1%e9%80%9a%e9%85%8d%e7%bd%ae%ef%bc%89
"ui:readonly": true
