### ISSUE TITLE
[Feature] 能否添加自定义验证属性, 如重复性验证，异步验证等

### ISSUE THREAD

**Issue by JLoveI** [alibaba/form-render#58]

**Comment by FateRiddle** [comment]
希望能详细说明一下使用场景哦。也欢迎加入到form-render的钉钉群交流

**Comment by JLoveI** [comment]
有些场景会出现需要和服务器通讯的验证，如用户名 邮箱已经被注册等，希望验证能支持多语言.

**Comment by tw93** [comment]
可以通过自定义组件来做：https://x-render.gitee.io/form-render/widgets
应该可以实现
