### ISSUE TITLE
[Bug]AntDesign 4 兼容问题

### ISSUE THREAD

**Issue by myonlylonely** [alibaba/form-render#60]
最新版本与Ant Design 4有兼容问题。
Ant Design 4的Icon修改了写法，导致有Icon的组件会报警告，并且图标无法显示。
如：
Warning: [antd: Button] `icon` is using ReactNode instead of string naming in v4.

**Comment by FateRiddle** [comment]
@myonlylonely 新升级了大版本 0.5.0
全面兼容antd。
