### ISSUE TITLE
[Bug] fusion主题 日期组件删除日期后，formDate的值会变成“Invalid date” 应该为“”。antd主题正常

### ISSUE THREAD

**Issue by sunguangjin** [alibaba/form-render#61]
- 在开 issue 前，可以先搜索以下以往的旧 [issue](https://github.com/alibaba/form-render/issues?utf8=%E2%9C%93&q=)，同时至少了解 [文档使用](https://alibaba.github.io/form-render/#/README)，你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正

- 开源项目的用户和维护者之间并不是甲方和乙方的关系，issue 也不是客服。
在开 issue 的时候，请抱着一种『一起合作来解决这个问题』的心态，同时请尽可能描述清楚，这样效率才会高

- 单纯的咨询问题请不要通过 issue 的方式来提交，很建议进钉钉群的方式来讨论

=====提交前删除上面说明=====

##### 1.formRender 对应的版本，fork [codeSandbox](https://codesandbox.io/s/form-render-8k1l5) 写一个最简可复现的版本，将内容贴到下面
 - formRender 版本号：
 - 可复现问题的 codeSandbox 地址：

##### 2.实际的效果以及期待效果或功能说明 
 - 实际的效果：
 - 期待的效果或功能：

**Comment by FateRiddle** [comment]
新版已经解决 @sunguangjin v0.5.0
