### ISSUE TITLE
[Feature]onChange中无法有效的区分init与change响应

### ISSUE THREAD

**Issue by height** [alibaba/form-render#62]
**Is your feature request related to a problem? Please describe.**
当我在基于该组件的onChange修改我的中心数据，但该组件在初始化时依旧会默认执行onChange，则会导致中心数据会被”无意义修改“，而且我从onChange中无法有效的区分init与change响应。

**Describe the solution you'd like**
提供一个onInitialize方法，如果onInitialize不为空，则组件对onChange的触发只会在用户操作表单时响应，可以称之为”onChange的严格模式“

**Describe alternatives you've considered**
如”onChange的严格模式“实现成本以及设计方案不被采纳，可以提供一个strictChange的props，能使其进入”onChange的严格模式“

**Comment by FateRiddle** [comment]
@height 新版已经解决。0.5.0
