### ISSUE TITLE
当schema第一层type为array时 ,vaild验证失效 ,一个是minItems这个长度验证, 和内部required必填验证都会失效

### ISSUE THREAD

**Issue by 1491614198** [alibaba/form-render#64]

**Comment by FateRiddle** [comment]
@1491614198 能否用codesandbox的demo复现一下问题？https://codesandbox.io/s/form-renderjichudemo-8k1l5

**Comment by 1491614198** [comment]
@FateRiddle   https://codesandbox.io/s/form-render-t2vot

**Comment by FateRiddle** [comment]
https://codesandbox.io/s/form-render-dhbs7
你在propsSchema的第一层就开始写内部结构了，写法错误啦：D
