### ISSUE TITLE
[Bug] 建议用antd的ConfigProvider组件语言包用"antd/lib/locale/zh_CN" 

### ISSUE THREAD

**Issue by onReadyL** [alibaba/form-render#68]
- formRender 版本号：0.5.0
 - 正常使用没问题，单测时出现的问题，没法复现

**Comment by onReadyL** [comment]
### 单测的环境：

- mocha ^6.2.0

- enzyme ^3.10.0

- chai ^4.2.0

**Comment by FateRiddle** [comment]
为啥单侧会失败，而且和语言包有什么关系？我不太明白。在清楚之前这个先hold。

**Comment by onReadyL** [comment]
> 为啥单侧会失败，而且和语言包有什么关系？我不太明白。在清楚之前这个先hold。

我重现了问题： https://gitlab.com/oReadyL/testProject.git
- yarn
-yarn test

**Comment by onReadyL** [comment]
@FateRiddle

**Comment by onReadyL** [comment]
> @FateRiddle

我还找到一个这个： https://github.com/ant-design/ant-design/issues/18702

**Comment by FateRiddle** [comment]
fixed
