### ISSUE TITLE
[Bug] 建议用antd的ConfigProvider组件语言包用"antd/lib/locale/zh_CN"

### ISSUE THREAD

**Issue by onReadyL** [alibaba/form-render#72]
单元测试时出现问题
 - formRender 版本号：0.5.0
 - 可复现问题的地址：https://gitlab.com/oReadyL/testProject.git
> git clone https://gitlab.com/oReadyL/testProject.git
> yarn
> yarn test

**Comment by FateRiddle** [comment]
fixed
