### ISSUE TITLE
[Bug]表单内容包含诸如<script>标签组报错

### ISSUE THREAD

**Issue by hoaresky** [alibaba/form-render#74]
内容：
![image](https://user-images.githubusercontent.com/25839923/76931820-7b80d000-6924-11ea-9d53-c5b24786b538.png)
报错：
![image](https://user-images.githubusercontent.com/25839923/76931846-863b6500-6924-11ea-9271-63aea72eef75.png)

**Comment by FateRiddle** [comment]
测试了下没有复现。先关闭了。
