### ISSUE TITLE
[Bug] Boolean 类型的 checkbox UI 不居中以及文字点击无效

### ISSUE THREAD

**Issue by Yokubee** [alibaba/form-render#76]
![image](https://user-images.githubusercontent.com/953545/77148555-bb81b780-6aca-11ea-83e1-13e1aa6efcc5.png)

demo 复现：
https://alibaba.github.io/form-render/docs/demo/index.html
选择完整例子 -> 一行两列 -> 左右排列
选择表单的 “是否显示颜色选择” 则复现

**Comment by FateRiddle** [comment]
fixed
