### ISSUE TITLE
[Bug] 来自用户输入的schema缺少校验

### ISSUE THREAD

**Issue by karzanOnline** [alibaba/form-render#79]
##### 1.formRender 对应的版本，fork [codeSandbox](https://codesandbox.io/s/form-render-8k1l5) 写一个最简可复现的版本，将内容贴到下面
 - formRender 版本号：0.5.3   
 - 可复现问题的 codeSandbox 地址：
https://codesandbox.io/s/form-render-bbxbh

![](https://img.alicdn.com/tfs/TB1HT7IAuL2gK0jSZPhXXahvXXa-950-1022.png)

##### 2.实际的效果以及期待效果或功能说明 
 - 实际的效果：
运行直接报错

 - 期待的效果或功能：
正常运行并提示错误信息

**Comment by FateRiddle** [comment]
已经解决，见changelog
