### ISSUE TITLE
[Feature] 可视化编辑器建设？开发中？

### ISSUE THREAD

**Issue by phnessu4** [alibaba/form-render#81]
**Is your feature request related to a problem? Please describe.**
看到进度表里面有这个任务卡，想问下当前开始开发了么，目前是否可用，进度如何？如果已经开始开发，在哪儿能看到？如何参与？

**Describe the solution you'd like**
目前公司项目考虑用form-render做解决方案，还在调研，如果确定采用，可能要开发一套表单可视化的编辑工具给非技术人员使用。

**Describe alternatives you've considered**
看到官方有排期计划，想了解下

**Additional context**
暂无

**Comment by phnessu4** [comment]
@FateRiddle 看到是你创建的任务，了解下情况，有无后续计划或者时间表？

**Comment by FateRiddle** [comment]
@phnessu4 进度大概在80%了。可以钉钉上找我聊。

**Comment by tw93** [comment]
@phnessu4 
https://form-render.github.io/schema-generator/  
希望你喜欢，欢迎来贡献~
