### ISSUE TITLE
[Feature]列表配置功能有待升级

### ISSUE THREAD

**Issue by chenai1112** [alibaba/form-render#84]
1. list列表收缩、展开状态，需要自定义，根据具体需求设置是展开、收缩状态

2. list列表 “新增”、“复制”按钮独占一行，form里有多条记录时，一屏展示记录太少，需要优化按钮位置

3. list表有多条记录时，合并状态难以找到自己需要的记录，希望可以定制，list收起后显示的内容

4. 多条记录难以看到总数，难以定位，希望提供列表索引、总记录条数

**Comment by FateRiddle** [comment]
已经加上了list的序号。详见新版的changelog 和在线demo的“新功能“。
其他诉求，我希望通过一个table类的array的替代展示组件来解决。在list上继续动刀的效果会比较有限。
