### ISSUE TITLE
[Bug]2个问题

### ISSUE THREAD

**Issue by dyyz1993** [alibaba/form-render#89]
1.如果object和array 是 disabled 和 readonly 那么应该继承下去。 需要在 map，和listHoc 继续p.disabled和p.readonly
2.当传入的 formData 里面有array类型的时候，且不是自定义组件，应该取formData的值。
文件 resolve.js 

if (type === 'array') {
    // 如果自定义组件
    // fix 当data 是存在的时候，应该继承，而不是赋予默认值
    if (widget||data ) return value;
    if (def && Array.isArray(def) && !value) {
      return def;
    }
    const subs = [].concat(items || []);
    const ret = [];
    value.forEach &&
      value.forEach((item, idx) => {
        ret[idx] = resolve(subs[idx] || subs[0], item, options);
      });
    return ret;
  }

**Comment by FateRiddle** [comment]
谢谢啊！已修复。array的readonly被赋予了别的意思，是array本身的那些功能不能操。disabled现在已经可以传递。另一个bug也修复了。
