### ISSUE TITLE
[Feature]如何定制一些简单的非表单元素,比如Alert和Divider

### ISSUE THREAD

**Issue by chenxiaolei** [alibaba/form-render#92]
不知道行不行

**Comment by FateRiddle** [comment]
为啥需要divider和alert？我倒是打算加modal, steps这些的

**Comment by chenxiaolei** [comment]
举个例而已, 目的实际是想让整个表单更丰满一点,  字段比较多的表单如果没有一些非表单元素，整个表单感觉非常单调

**Comment by tw93** [comment]
可见 https://github.com/alibaba/form-render/blob/master/CHANGELOG.md#056
