### ISSUE TITLE
[Feature]能否支持oneOf,anyOf

### ISSUE THREAD

**Issue by dyyz1993** [alibaba/form-render#99]
属于schema的属性，在实际场景有一定的用处。例如：描述一个对象多个展示类型的时候，可以自由切换，本人实际应用场景，作为可视化属性编辑面板，一个属性多个类型，string/boolean/object,等，都会有不同的含义，如果可以让用户可以选择输入的类型。那么是否更符合schema标准。

**Comment by YiuTerran** [comment]
v7里面还有`if` `then` `else`标签，可以考虑拿来做联动设计

**Comment by FateRiddle** [comment]
看过了react-jsonschema-form里one of的例子，可以使用ui:hidden的条件表达式来做。
@YiuTerran form-render只是参考了JSON schema的规范，但毕竟JSON schema没有函数表达式等其他选项，而且是校验数据的规范并不是描述表单UI的规范，所以我们在设计上不会完全照抄（特别是过于复杂的描述方式），例如if then else，写得太麻烦，对用户不友好，这些完全可以通过字段的函数表达式来做（[如何联动](https://alibaba.github.io/form-render/#/docs/function)）
目前不打算支持这两个语法。
